/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as ProfilUserIdRouteImport } from './routes/profil.$userId'
import { Route as PlayerChapterIdRouteImport } from './routes/player.$chapterId'
import { Route as ModuleModuleIdRouteImport } from './routes/module.$moduleId'
import { Route as MessagesUserIdRouteImport } from './routes/messages.$userId'
import { Route as AdminStudentUserIdRouteImport } from './routes/admin_.student.$userId'
import { Route as AdminStudentUserIdDmsRouteImport } from './routes/admin_.student.$userId.dms'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilUserIdRoute = ProfilUserIdRouteImport.update({
  id: '/profil/$userId',
  path: '/profil/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerChapterIdRoute = PlayerChapterIdRouteImport.update({
  id: '/player/$chapterId',
  path: '/player/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleModuleIdRoute = ModuleModuleIdRouteImport.update({
  id: '/module/$moduleId',
  path: '/module/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUserIdRoute = MessagesUserIdRouteImport.update({
  id: '/messages/$userId',
  path: '/messages/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentUserIdRoute = AdminStudentUserIdRouteImport.update({
  id: '/admin_/student/$userId',
  path: '/admin/student/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentUserIdDmsRoute = AdminStudentUserIdDmsRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => AdminStudentUserIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
  '/player/$chapterId': typeof PlayerChapterIdRoute
  '/profil/$userId': typeof ProfilUserIdRoute
  '/messages/': typeof MessagesIndexRoute
  '/admin/student/$userId': typeof AdminStudentUserIdRouteWithChildren
  '/admin/student/$userId/dms': typeof AdminStudentUserIdDmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
  '/player/$chapterId': typeof PlayerChapterIdRoute
  '/profil/$userId': typeof ProfilUserIdRoute
  '/messages': typeof MessagesIndexRoute
  '/admin/student/$userId': typeof AdminStudentUserIdRouteWithChildren
  '/admin/student/$userId/dms': typeof AdminStudentUserIdDmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
  '/player/$chapterId': typeof PlayerChapterIdRoute
  '/profil/$userId': typeof ProfilUserIdRoute
  '/messages/': typeof MessagesIndexRoute
  '/admin_/student/$userId': typeof AdminStudentUserIdRouteWithChildren
  '/admin_/student/$userId/dms': typeof AdminStudentUserIdDmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/messages/$userId'
    | '/module/$moduleId'
    | '/player/$chapterId'
    | '/profil/$userId'
    | '/messages/'
    | '/admin/student/$userId'
    | '/admin/student/$userId/dms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/messages/$userId'
    | '/module/$moduleId'
    | '/player/$chapterId'
    | '/profil/$userId'
    | '/messages'
    | '/admin/student/$userId'
    | '/admin/student/$userId/dms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/messages/$userId'
    | '/module/$moduleId'
    | '/player/$chapterId'
    | '/profil/$userId'
    | '/messages/'
    | '/admin_/student/$userId'
    | '/admin_/student/$userId/dms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  MessagesUserIdRoute: typeof MessagesUserIdRoute
  ModuleModuleIdRoute: typeof ModuleModuleIdRoute
  PlayerChapterIdRoute: typeof PlayerChapterIdRoute
  ProfilUserIdRoute: typeof ProfilUserIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  AdminStudentUserIdRoute: typeof AdminStudentUserIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$userId': {
      id: '/profil/$userId'
      path: '/profil/$userId'
      fullPath: '/profil/$userId'
      preLoaderRoute: typeof ProfilUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$chapterId': {
      id: '/player/$chapterId'
      path: '/player/$chapterId'
      fullPath: '/player/$chapterId'
      preLoaderRoute: typeof PlayerChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/$moduleId': {
      id: '/module/$moduleId'
      path: '/module/$moduleId'
      fullPath: '/module/$moduleId'
      preLoaderRoute: typeof ModuleModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$userId': {
      id: '/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof MessagesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/student/$userId': {
      id: '/admin_/student/$userId'
      path: '/admin/student/$userId'
      fullPath: '/admin/student/$userId'
      preLoaderRoute: typeof AdminStudentUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/student/$userId/dms': {
      id: '/admin_/student/$userId/dms'
      path: '/dms'
      fullPath: '/admin/student/$userId/dms'
      preLoaderRoute: typeof AdminStudentUserIdDmsRouteImport
      parentRoute: typeof AdminStudentUserIdRoute
    }
  }
}

interface AdminStudentUserIdRouteChildren {
  AdminStudentUserIdDmsRoute: typeof AdminStudentUserIdDmsRoute
}

const AdminStudentUserIdRouteChildren: AdminStudentUserIdRouteChildren = {
  AdminStudentUserIdDmsRoute: AdminStudentUserIdDmsRoute,
}

const AdminStudentUserIdRouteWithChildren =
  AdminStudentUserIdRoute._addFileChildren(AdminStudentUserIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  MessagesUserIdRoute: MessagesUserIdRoute,
  ModuleModuleIdRoute: ModuleModuleIdRoute,
  PlayerChapterIdRoute: PlayerChapterIdRoute,
  ProfilUserIdRoute: ProfilUserIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  AdminStudentUserIdRoute: AdminStudentUserIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
